### PR TITLE
Ckan 2.9 datafile page

### PR DESCRIPTION
**Pull request by Alexandra-Green**
## What this PR accomplishes

Updates the UI of the Datafile page.

## Issue(s) addressed

- Update the styling of the “Download” button to be a list instead, that includes the downloadable formats
- Add in a box for the Visualize data (for machine readable data files). The image and text is static
- Add the report an error form
- Remove the “Resources” table with the links. It’s no longer needed
- “Additional information” section: fields that are empty should not be shown in the box. For example, if a dataset has an empty Maintainer field, it should not appear in the “Additional information” section
- Add the feedback form
- Adds consistent dark overlay behind menu drop down on datafile page

## What needs review

- Styling of right aside for download/access data formats and visualize data are consistent with the Figma and are responsive. (**Note: the datafile page has 2 figma frames, one for preview pages and one for download/about pages**)
- Translation for asides are correct
- The report an error form is aligned to figma, translated and redirects to correct page
- The feedback form is aligned to figma, translated and redirects to correct page
- The resources table is removed 
- When opening the dropdown on the datafile page, the overlay is consistently dark on the page
- The empty fields in the additional information tables are not displayed. 
- Additional information table is aligned with Figma and translations are correct

### Notes

- Data api aside styling is present but commented out, once the ticket to display the button on stage is completed the comments can be removed. 
- I've added the condition to show the access data aside found in the about/download page on the Figma to resources when the datastore is not active. Because users would not be able to visualize the data or download the different formats when the datastore is not active, the access data box seemed appropriate. 
- There is no alt text for the static image
- Not sure why, but there is two resource_read.html in the internal folder.

### CODE REVIEW

**Comment by KatiRG** [comment]
French translation document (5.1) shows that "Download data" should be "Télécharger des données" not _les_ données

**Comment by KatiRG** [comment]
"File size" in additional tables does not translate:
Screen Shot 2023-02-28 at 14 12 48

**Comment by KatiRG** [comment]
Ready for merge after the above comments. Well done!!!

**Comment by Alexandra-Green** [comment]
> Missing the "Data Visualizer" heading

Should be good now, but when the designers review the ticket, can they review the aside heading versus the Data visualizer one? The aside is higher on the hierarchy than the Data Visualizer, but the aside headings are `<h3>`s and Data Visualizer is an `h2`

**Comment by KatiRG** [comment]
> > Missing the "Data Visualizer" heading
> 
> Should be good now, but when the designers review the ticket, can they review the aside heading versus the Data visualizer one? The aside is higher on the hierarchy than the Data Visualizer, but the aside headings are `<h3>`s and Data Visualizer is an `h2`

Will make a note in the ticket, thanks!

**Comment by KatiRG** [comment]
> Not sure why, but there is two resource_read.html in the internal folder.
Seems like one extends the other:

`scheming/package/resource_read.html`:
```
{#
  Override scheming to modify the excluded_fields and set the 
  bi-lingual description for resources.
#}
{% extends "package/resource_read.html" %}
```

**Pull request merged**
