### PR TITLE
[Task]: Change facet pills in search box

### PR DESCRIPTION
**Pull request by Alexandra-Green**
## What this PR accomplishes

- Add clear filters button when a facet filter is applied.
- Change the style of the facet pills when in mobile and on desktop screens

## Issue(s) addressed

- DATA-1405

## What needs review

On desktop:

- Search pills are located under the highlight box.
- Category name is placed outside of the search pill.
- A tertiary button “Clear filters“ is placed at the end of the pills chain. This button clears all filters values except Access level filter.
- Colours and states match figma 

On mobile:

- the pills are placed under Filters button. Each category starts with a new line.
- Clear filters button starts with a new line as well and work
- Colours match figma

### CODE REVIEW

**Comment by KatiRG** [comment]
"Clear filters" link does not translate to French:
Screenshot 2024-03-12 at 10 56 54

**Comment by KatiRG** [comment]
The "Clear filters" link is misaligned:
Screenshot 2024-03-12 at 11 06 08

**Comment by KatiRG** [comment]
On desktop:

- [ ] Search pills are located under the highlight box.
- [ ]     Category name is placed outside of the search pill.
- [ ]     A tertiary button “Clear filters“ is placed at the end of the pills chain. This button clears all filters values except Access level filter.
- [ ]     Colours and states match figma

On mobile:

- [ ]     the pills are placed under Filters button. Each category starts with a new line.
- [ ]     Clear filters button starts with a new line as well and work
- [ ]     Colours match figma

**Review by KatiRG — CHANGES_REQUESTED** [review]
minor fixes on layout/translation

**Comment by Alexandra-Green** [comment]
@KatiRG There is no translation for the button as of yet, we can create another ticket/PR once it is received.

**Review by KatiRG — APPROVED** [review]

**Pull request merged**
